---
openstack_venv: "{{ ansible_facts.user_dir }}/deployment/venvs/openstack-config"

openstack_projects:
  - "{{ openstack_compute_project }}"

openstack_compute_project:
  name: compute
  description: OpenStack compute project
  project_domain: default
  user_domain: default
  users: "{{ openstack_compute_users }}"
  keypairs:
    - name: jackphodgkiss_ed25519
      public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILQech30mi+U14dLiM8e9EbW3A3Z+tMWUjSbfVvgAp9v jack@prometheus.local
  quotas: "{{ openstack_unlimited_quotas }}"

openstack_compute_users:
  - name: jackphodgkiss
    description: Jack Hodgkiss
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63386134663065653030663461373063343865323362353434303235376638613765316230303466
          6361623334353962353161313538393831623636656632350a376264343134356436383735316331
          37343833313138356531323135353133366664613764623466326630613936343661663833343431
          6635356161366261380a366564383736356265356639373965313335396361313430303138616335
          32656565656562303361376530663862636137316138333362313739386634653434653430656530
          3063646661656137313538636233306430623331663534643564
    email: identity@jackhodgkiss.uk
    roles: "{{ openstack_admin_roles }}"

openstack_admin_roles:
  - admin
  - load-balancer_admin

openstack_user_roles:
  - member
  - load-balancer_member
  - observer

openstack_unlimited_quotas:
  backup_gigabytes: -1
  backups: -1
  cores: -1
  floatingip: -1
  gigabytes: -1
  injected_file_size: -1
  injected_files: -1
  instances: -1
  key_pairs: -1
  per_volume_gigabytes: -1
  ram: -1
  security_group: -1
  security_group_rule: -1
  snapshots: -1
  volumes: -1

openstack_flavors:
  - "{{ openstack_flavor_m1_tiny }}"
  - "{{ openstack_flavor_m1_small }}"
  - "{{ openstack_flavor_m1_medium }}"
  - "{{ openstack_flavor_m1_large }}"

openstack_flavor_m1_tiny:
  name: "m1.tiny"
  ram: 512
  disk: 16
  vcpus: 1

openstack_flavor_m1_small:
  name: "m1.small"
  ram: 1024
  disk: 32
  vcpus: 2

openstack_flavor_m1_medium:
  name: "m1.medium"
  ram: 2048
  disk: 64
  vcpus: 3

openstack_flavor_m1_large:
  name: "m1.large"
  ram: 4096
  disk: 128
  vcpus: 4

# List of additional host packages.
os_images_package_dependencies_extra:
  # debootstrap is required to build ubuntu-minimal images.
  - debootstrap

# Drop cloud-init and stable-interface-names from default elements.
os_images_common: enable-serial-console

# Set this to true to force rebuilding images.
os_images_force_rebuild: false

openstack_images:
  - "{{ openstack_image_cirros_0_6_2 }}"
  - "{{ openstack_image_ubuntu_2204 }}"
  - "{{ openstack_image_ubuntu_2404 }}"

openstack_image_cirros_0_6_2:
  name: "Cirros 6.2"
  type: qcow2
  image_url: "https://github.com/cirros-dev/cirros/releases/download/0.6.2/cirros-0.6.2-aarch64-disk.img"
  is_public: True
  properties:
    os_type: "linux"
    os_distro: "cirros"
    os_version: "0.6.2"
    hw_rng_model: "virtio"

openstack_image_ubuntu_2204:
  name: "Ubuntu 22.04"
  type: qcow2
  image_url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-arm64.img"
  is_public: True
  properties:
    os_type: "linux"
    os_distro: "Ubuntu"
    os_version: "22.04"
    hw_rng_model: "virtio"

openstack_image_ubuntu_2404:
  name: "Ubuntu 24.04"
  type: qcow2
  image_url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-arm64.img
  is_public: true
  properties:
    os_type: "linux"
    os_distro: "Ubuntu"
    os_version: "24.04"
    hw_rng_model: "virtio"

openstack_networks:
  - "{{ openstack_network_external }}"
  - "{{ openstack_network_admin_vlan }}"
  - "{{ openstack_network_compute_vlan }}"

openstack_network_external_name: "external"

openstack_network_external:
  name: "{{ openstack_network_external_name }}"
  project: "admin"
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  provider_segmentation_id: 40
  shared: true
  external: true
  subnets:
    - "{{ openstack_subnet_external }}"

openstack_subnet_external:
  name: "{{ openstack_network_external_name }}"
  project: "admin"
  cidr: "10.0.40.0/24"
  gateway_ip: "10.0.40.254"
  allocation_pool_start: "10.0.40.200"
  allocation_pool_end: "10.0.40.249"

openstack_network_admin_vlan_name: "admin-vlan"

openstack_network_admin_vlan:
  name: "{{ openstack_network_admin_vlan_name }}"
  project: admin
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  shared: false
  subnets:
    - "{{ openstack_subnet_admin_vlan }}"

openstack_subnet_admin_vlan:
  name: "{{ openstack_network_admin_vlan_name }}"
  project: admin
  cidr: "172.20.0.0/24"
  gateway_ip: "172.20.0.254"
  allocation_pool_start: "172.20.0.1"
  allocation_pool_end: "172.20.0.253"

openstack_routers:
  - "{{ openstack_router_admin }}"
  - "{{ openstack_router_compute }}"

openstack_router_admin:
  - name: admin
    project: admin
    interfaces:
      - "{{ openstack_network_admin_vlan_name }}"
    network: "{{ openstack_network_external_name }}"

openstack_network_compute_vlan_name: "compute-vlan"

openstack_network_compute_vlan:
  name: "{{ openstack_network_compute_vlan_name }}"
  project: compute
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  shared: false
  subnets:
    - "{{ openstack_subnet_compute_vlan }}"

openstack_subnet_compute_vlan:
  name: "{{ openstack_network_compute_vlan_name }}"
  project: compute
  cidr: "10.141.0.0/24"
  gateway_ip: "10.141.0.254"
  allocation_pool_start: "10.141.0.1"
  allocation_pool_end: "10.141.0.253"

openstack_router_compute:
  - name: compute
    project: compute
    interfaces:
      - "{{ openstack_network_compute_vlan_name }}"
    network: "{{ openstack_network_external_name }}"

openstack_security_groups:
  - name: default
    project: admin
    rules:
      - protocol: icmp
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
  - name: default
    project: compute
    rules:
      - protocol: icmp
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
